// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irvwskbwbkxqvenkhztf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlydndza2J3Ymt4cXZlbmtoenRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMDgyOTUsImV4cCI6MjA1MzY4NDI5NX0.LCwFg_Rm5CFGXBH1bn9C7oRPVszS6jf7b2p1WPFzOLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);